services:
  - type: web
    name: secure-webapp
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        value: jdbc:mysql://localhost:3306/userswa?useSSL=false&allowPublicKeyRetrieval=true
      - key: ENCRYPTION_KEY
        value: wDilk954ZQPZWGpysSVJbw==
